model_selection:
    model:
      RandomForest:
         search_param_grid:
           n_estimators: [100, 200]
           max_depth: [10, 15]
           criterion: ["gini", "entropy"]

      KNN:
        search_param_grid:
           n_neighbors: [3, 5, 7]
           weights: ["uniform", "distance"]
           algorithm: ["ball_tree", "kd_tree"]

      LogisticRegression:
       search_param_grid:
          penalty: ["l2", "l1"]
          C: [0.01, 0.1, 1.0]
          solver: ["lbfgs", "liblinear"]
          max_iter: [500, 1000, 2000]
       